services:
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sql_server_db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: Passw0rd@123
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
    driver: local
